### PR TITLE
Update intercom.md

### PR DESCRIPTION
**Pull request by Brandoncharleskhoo1**
- This integration requires OAuth during the setup phase, available on Amplitude paid plans only.

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

### CODE REVIEW

**Comment by Brandoncharleskhoo1** [comment]
Added this callout to set expectations with future customers. This integration requires OAuth during the setup phase, available on Amplitude paid plans only.

**Review by Leoaqr — APPROVED** [review]

**Comment by bgiori** [comment]
@Brandoncharleskhoo1 is this still in the works or can be closed?

**Comment by Brandoncharleskhoo1** [comment]
@bgiori Do you have to approve this or Cynthia?

**Comment by ampcynthli** [comment]
@Brandoncharleskhoo1 Brian will have to approve and merge

**Comment by kevinpagtakhan** [comment]
@bgiori @justin-fiedler can we get this PR reviewed?

**Pull request merged**
