### PR TITLE
Create WebEngage-cohort.md

### PR DESCRIPTION
**Pull request by Brandoncharleskhoo1**
# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

### CODE REVIEW

**Comment by Brandoncharleskhoo1** [comment]
@markzegarelli i don't know why it's failing the spell checker. It doesn't seem to recognize "WebEngage" so I tried Web-engage and other variations but it keeps failing. Is there anyway we can skip the spell checker? 🐱

**Review by markzegarelli — APPROVED** [review]
@Brandoncharleskhoo1 This should be good to go!

**Comment by Brandoncharleskhoo1** [comment]
@markzegarelli how do I resolve this flag ".github/styles/Vocab/dev/accept.txt?

**Comment by markzegarelli** [comment]
@Brandoncharleskhoo1 Should be all set!

**Pull request merged**
