### PR TITLE
Update experiment screenshots for new tab redesign

### PR DESCRIPTION
**Pull request by shelleywang**
# Dev Docs PR

## Description

- Local evaluation is GA so I removed language around enabling the flag
- Updated screenshots of the main experiment view with where different settings can be found after the tab redesign 

## Deadline

Not urgent but the tab redesign went live last Friday

## Change type

- [x] Doc update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs
@caseyamp

### CODE REVIEW

**Comment by bgiori** [comment]
Looks beautiful. 

My only concerns are:
(a) the flag name in the screenshots does not follow the guide (guide tells you to create a flag called "Getting Started" whereas the screenshots show "A Great Flag")
(b) The activation screenshot does not have deployments added, would be good to add a deployment recommended in the previous "create a deployment" article (e.g. `web`)

**Comment by shelleywang** [comment]
@bgiori I ended up just removing the examples for the flag name and description from the text so there wasn't the inconsistency with the screenshots. 

ready for review again

**Review by bgiori — APPROVED** [review]
Approved pending one change. In the `Track Exposure` page of the getting started guide, the interactive api table sets `getting-started` as the flag key by default. Can you remove the default value?

**Comment by bgiori** [comment]
Screen Shot 2022-08-30 at 11 17 59 AM

**Pull request merged**
